### ISSUE TITLE
Script to report SQF->C++ conversion percentage.

### ISSUE THREAD

**Issue by NouberNou** [NouberNou/intercept#11]
Parse the [contents of this file](https://github.com/NouberNou/intercept/blob/master/src/client/intercept/client/sqf_pointers_declaration.hpp), getting the names of the function pointers. Then search [this folder](https://github.com/NouberNou/intercept/tree/master/src/client/intercept/client/sqf) if they are referenced or not. If they are not referenced it is assumed that no wrapper exists for that function.

This should be an easy way to look at our code coverage in wrappers.

@jaynus @Glowbal You are more Python masters than I am.

**Comment by Glowbal** [comment]
Current stats:
```
Unary functions declared: 1070
Binary functions declared: 968
Nular functions declared: 221
Unary functions used: 10
Binary functions used: 10
Nular functions used: 1
```

I am working on having this output a markdown formatted table and update a github issue (#13) with it.

**Comment by Glowbal** [comment]
See #13 for output generated.

**Comment by Glowbal** [comment]
Done

**Comment by Glowbal** [comment]
Every push to master will trigger a travis build and it will check the source files for the declared functions. If any of the source files (.cpp) contains a match, it will assume that it's properly implemented in the wrapper and mark is at completed.

It also calculates the percentage completed and puts that on top.

Functions are ordered by type (unary, binary and nular). The completed ones are always on the bottom of each list. There is no need for you to mark or add new functions as completed - it's all done through travis.
