### ISSUE TITLE
Travis CI and automatic command coverage update

### ISSUE THREAD

**Issue by jonpas** [NouberNou/intercept#12]
Noticed @NouberNou talking about automatic update of the command-wrapper coverage, why not throw Travis in the play for compilation checks and whatnot, then juts call a script that will run after every merge/push to master and update the coverage (wherever that will be).

**Comment by Glowbal** [comment]
Yes, good idea. @NouberNou already enabled travis for intercept. I am currently writing the python scripts for it. Should be up and running later today. See #11

**Comment by jonpas** [comment]
:+1:
