### ISSUE TITLE
Complex return types from SQF functions.

### ISSUE THREAD

**Issue by NouberNou** [NouberNou/intercept#4]
Since SQF is dynamically typed, arrays can contain many different variables. Dealing with complex returns from SQF functions that might contain multiple types of data needs to be handled in a way that is maintainable, yet also developer friendly.

I feel that specific structs would work the best, or arrays of structs (well not arrays, some STL container obviously), since we could implement proper, unambiguous names for the returned data.

For example the function [lineIntersectsSurfaces](https://community.bistudio.com/wiki/lineIntersectsSurfaces) returns an array of arrays containing the follow data:

```
intersectPosASL - the actual position where line intersects 1st surface
surfaceNormal - a normal to the intersected surface
intersectObject - the object the surface belongs to (could be proxy object)
parentObject - the object proxy object belongs to (not always the same as intersect object)
```

This could easily be turned into an array of specific structs for that return type, though the drawback is that it would be a specific struct related _only to that specific function_.

The alternative is to use an implementation of an `any` type map or tuple (suggested by @jaynus). I feel this though would add overhead and complexity to the developer, but it'd be more maintainable to the library.

**Comment by Glowbal** [comment]
We are going to add another abstraction layer on top of this anyway, no? So it might be best to go with the easiest and simplist solution.

I think we would want to stick as close to the original format as we can. Some struct implementation might work. I don't see anything wrong with having a specific struct for this function.

**Comment by dbenson24** [comment]
Creating and maintaining a struct for every single SQF function is going to be challenging. Plus you also have to consider a scenario where someone uses unary__call__code__ret__any. This could potentially invoke a script that returns an array of arrays of arrays, or it could just return an integer, we'd have no way of knowing that before hand. Maybe a hybrid solution is possible? One that uses structs for some of the more well defined functions and then reverting to a map/tuple situation when the SQF return type is unknown

**Comment by jaynus** [comment]
I advised Nou against the struct idea and to use generic container types. it's been worked on.

**Comment by NouberNou** [comment]
I am still planning on using structs for return types from SQF functions. They all return standard return types, or arrays of standard structures that can be replicated as structs. I feel that structs are the most logical choice for these as they provide named access to often confusing components.

The point of this project is not always to be easy for us as developers of it, but to be easy for end users wishing to use Intercept and Arma as a platform for development. I think the added undertaking of developing and maintaining structs for certain functions is totally reasonable and justified in that sense.

As for using the call function, that is an entirely different scenario, as it is calling SQF functions. We have no ability to control that.

1) It should be discouraged in the first place.
2) Providing that the developer is the same for both the SQF code and the Intercept code, they should know at compile time what the types will be, so a tuple is probably going to be the best option.

**Comment by dbenson24** [comment]
With all of the pre-existing code that's been written in SQF, I think it's kind of absurd to tell anyone that wants to use intercept that they shouldn't utilize the call command. I understand your point about wanting to use structs, but at the same time we could implement a named component scheme using a Map that would be more maintainable in the long run and allow for easier handling in situations when we don't know what is being returned.

**Comment by Verox-** [comment]
We've ended up using structs for this purpose.
