### ISSUE TITLE
Casting game_value directly to int doesn't work properly

### ISSUE THREAD

**Issue by esteldunedain** [NouberNou/intercept#62]
Suppose I have a variable on the missionNamespace such that:

```sqf
myVariable = 2;
```

In Intercept:
```c++
int myVariable = sqf::get_variable(sqf::mission_namespace(), "myVariable");
```
compiles fine but returns `0`.

To get the correct result you need to do:
```c++
int myVariable = float(sqf::get_variable(sqf::mission_namespace(), "myVariable"));
```

------------------

The opposite cast, converting `int` to `game_value` doesn't compile at all:

```c++
game_value value(2);
```
```
Error	C2668	'intercept::types::game_value::game_value': ambiguous call to overloaded function
```

**Comment by Glowbal** [comment]
sqf does not know `int`, but only `float`. All numbers are floats. So having to cast it to a float before putting it into a game_value isn't that wierd.

**Comment by esteldunedain** [comment]
> So having to cast it to a float before putting it into a game_value isn't that wierd.

True, it's more of an inconvenience. However the first part is a bug.

**Comment by Verox-** [comment]
There's no integer coercion defined for game_value

**Comment by Verox-** [comment]
Should be fixed with c3d72b630c2e9f9463e78048b5facc2ec5bccb00

**Comment by NouberNou** [comment]
Is this still ongoing?

**Comment by Verox-** [comment]
Can close
